### ISSUE TITLE
About the demo

### ISSUE THREAD

**Issue by Charlottecuc** [chomeyama/HN-UnifiedSourceFilterGAN#1]
Hi. Thank you for your great work. Do you have any kind of demo page which shows audio samples of the model (and maybe samples for comparison as you mentioned in the paper)?
Thanks!

**Comment by chomeyama** [comment]
Thanks for your interest in my research!
Sorry for the delay in preparing the demo site. Now I prepared it [here](https://chomeyama.github.io/HN-UnifiedSourceFilterGAN-Demo/).
